// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxEXIr7hCLD7z88gWKbCJw8UIFe8i92s',
    appId: '1:904853707508:web:70fb75e901f2947e389ca1',
    messagingSenderId: '904853707508',
    projectId: 'moonpv-9b71b',
    authDomain: 'moonpv-9b71b.firebaseapp.com',
    storageBucket: 'moonpv-9b71b.appspot.com',
    measurementId: 'G-9P3PNSG8N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqvS5nlggoSbLjz5vcmF3rHdirQLieMhc',
    appId: '1:904853707508:android:2dbfeddc4e75155c389ca1',
    messagingSenderId: '904853707508',
    projectId: 'moonpv-9b71b',
    storageBucket: 'moonpv-9b71b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUuM170EVd6YukTd3AH6AYkWtGh7z0qpc',
    appId: '1:904853707508:ios:d01840d60869d65c389ca1',
    messagingSenderId: '904853707508',
    projectId: 'moonpv-9b71b',
    storageBucket: 'moonpv-9b71b.appspot.com',
    androidClientId: '904853707508-v6v2ubk5naqcbch407go333bqel76kt8.apps.googleusercontent.com',
    iosClientId: '904853707508-rsmbt368keakgllp8qsascmpocmgg0v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.moonpv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUuM170EVd6YukTd3AH6AYkWtGh7z0qpc',
    appId: '1:904853707508:ios:d01840d60869d65c389ca1',
    messagingSenderId: '904853707508',
    projectId: 'moonpv-9b71b',
    storageBucket: 'moonpv-9b71b.appspot.com',
    androidClientId: '904853707508-v6v2ubk5naqcbch407go333bqel76kt8.apps.googleusercontent.com',
    iosClientId: '904853707508-rsmbt368keakgllp8qsascmpocmgg0v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.moonpv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhxEXIr7hCLD7z88gWKbCJw8UIFe8i92s',
    appId: '1:904853707508:web:27b31fe1a1b3c9ac389ca1',
    messagingSenderId: '904853707508',
    projectId: 'moonpv-9b71b',
    authDomain: 'moonpv-9b71b.firebaseapp.com',
    storageBucket: 'moonpv-9b71b.appspot.com',
    measurementId: 'G-ZY895HPKSL',
  );

}